>>> def calculate_momentum():
...     calculate_momentum
...     mass = float(input("Enter the object's mass (in kilograms): "))
...
>>> v
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    v
NameError: name 'v' is not defined
>>> mass = float(input("Enter the object's mass (in kilograms): "))
Enter the object's mass (in kilograms): 5
>>> velocity = float(input("Enter the object's velocity (in meters per second): "))
Enter the object's velocity (in meters per second): 8
>>> momentum = mass * velocity
>>> print(f"The object's momentum is: {momentum} kg m/s")
The object's momentum is: 40.0 kg m/s
>>>
